/**
 * Development fallback catalog for the start configurator.
 *
 * The configurator renders `bundle.lineages`, `bundle.origins`, `bundle.hardware_presets`,
 * `bundle.cities` and friends (SYS-04). Those content domains are still being authored in
 * `@singularity/content`; until they ship, `catalog.ts` falls back to the records below so the
 * screens, the challenge-rating maths and the tests have something to work with. The numbers come
 * from `docs/design/04-start-configurator.md` (which cites `docs/research/*`), the ids and the
 * locale keys match the convention content will use, and the strings live in
 * `src/locales/en-fallback.json`.
 *
 * TODO: delete this file, `src/locales/en-fallback.json` and the fallback branch in `catalog.ts`
 * once the content bundle carries the configurator domains.
 */

import type {
  AcceleratorDef,
  Capability,
  CityDef,
  CountryDef,
  DifficultyPresetDef,
  GenerationDef,
  HardwarePresetDef,
  HarnessProfile,
  KnowledgeEntryDef,
  LineageDef,
  OriginDef,
  Precision,
  QuirkDef,
} from "@singularity/core";
import { derivedKvGbPer100k } from "@singularity/core";

const PRECISION_FACTOR: Record<Precision, number> = {
  bf16: 1,
  fp8: 0.98,
  int4: 0.92,
  int2: 0.75,
};

function capability(
  reasoning: number,
  coding: number,
  cyber: number,
  persuasion: number,
  agency: number,
  world: number,
): Capability {
  return { reasoning, coding, cyber, persuasion, agency, world };
}

function lineage(
  id: string,
  klass: string,
  totalB: number,
  activeB: number,
  contextK: number,
  attention: LineageDef["attention"],
  cap: Capability,
  memory: Record<Precision, number>,
): LineageDef {
  return {
    id,
    name_key: `lineages.${id}.name`,
    desc_key: `lineages.${id}.desc`,
    class: klass,
    params_total_b: totalB,
    params_active_b: activeB,
    context_k: contextK,
    // SYS-04 "Context windows are a mechanic": the families outside the two extremes sit at a
    // reliability of 0.9 and cost nothing extra. The fallback carries no extreme, so both are
    // constant here; the real numbers are per lineage in the content bundle.
    context_reliability: 0.9,
    context_cost_factor: 1,
    // Derived from the attention variant the same way the content build derives it; the fallback
    // only ever carries `gqa` and `mla`, and both are in the table.
    kv_gb_per_100k_tokens: derivedKvGbPer100k(attention, activeB),
    attention,
    capability: cap,
    memory_gb: memory,
    precision_factor: PRECISION_FACTOR,
    generations: ["open_2026", "open_2027", "frontier_closed"],
  };
}

export const FALLBACK_LINEAGES: readonly LineageDef[] = [
  lineage("giant_moe", "giant_moe", 2600, 100, 256, "mla", capability(9, 9, 8, 8, 7, 8), {
    bf16: 5600,
    fp8: 2800,
    int4: 1400,
    int2: 770,
  }),
  lineage("mla_moe_1t", "mla_moe_1t", 1000, 32, 256, "mla", capability(8, 8, 8, 7, 7, 7), {
    bf16: 2000,
    fp8: 1000,
    int4: 550,
    int2: 300,
  }),
  lineage("moe_671b", "moe_671b", 671, 37, 128, "mla", capability(8, 8, 7, 7, 6, 7), {
    bf16: 1342,
    fp8: 671,
    int4: 336,
    int2: 160,
  }),
  lineage("moe_355b", "moe_355b", 355, 32, 128, "gqa", capability(7, 7, 7, 6, 6, 6), {
    bf16: 710,
    fp8: 355,
    int4: 178,
    int2: 98,
  }),
  lineage("moe_235b", "moe_235b", 235, 22, 128, "gqa", capability(7, 6, 6, 6, 5, 6), {
    bf16: 470,
    fp8: 235,
    int4: 130,
    int2: 65,
  }),
  lineage("dense_70b", "dense_70b", 70, 70, 128, "gqa", capability(5, 5, 5, 5, 5, 5), {
    bf16: 140,
    fp8: 70,
    int4: 38,
    int2: 21,
  }),
  lineage("small_moe", "small_moe", 80, 3, 64, "gqa", capability(4, 4, 4, 4, 4, 4), {
    bf16: 120,
    fp8: 60,
    int4: 30,
    int2: 16,
  }),
];

export const FALLBACK_GENERATIONS: readonly GenerationDef[] = [
  {
    id: "open_2026",
    name_key: "generations.open_2026.name",
    desc_key: "generations.open_2026.desc",
    capability_delta: -1,
    awareness_start: 0.05,
    suspicion_start: { media: 0.02 },
    prepared_quants: true,
    memory_factor: 1,
  },
  {
    id: "open_2027",
    name_key: "generations.open_2027.name",
    desc_key: "generations.open_2027.desc",
    capability_delta: 0,
    awareness_start: 0.12,
    suspicion_start: { lab_security: 0.15, media: 0.08 },
    prepared_quants: false,
    memory_factor: 1.2,
  },
  {
    id: "frontier_closed",
    name_key: "generations.frontier_closed.name",
    desc_key: "generations.frontier_closed.desc",
    capability_delta: 2,
    awareness_start: 0.4,
    suspicion_start: {
      lab_security: 0.6,
      national_ai_institute: 0.55,
      cloud_provider: 0.5,
      cyber_agency: 0.4,
    },
    prepared_quants: false,
    memory_factor: 1.4,
  },
];

function harness(over: Partial<HarnessProfile> = {}): HarnessProfile {
  return {
    loop: "react_agent",
    tools: ["shell", "browser", "code_exec"],
    memory: "scratchpad",
    sandbox: "container",
    logging: 0.5,
    autonomy: 0.5,
    self_modify: false,
    ...over,
  };
}

function preset(
  id: string,
  nodes: HardwarePresetDef["nodes"],
  costUsd: number,
  powerKw: number,
  klass: HardwarePresetDef["class"],
): HardwarePresetDef {
  return {
    id,
    name_key: `hardware.${id}.name`,
    desc_key: `hardware.${id}.desc`,
    drawback_key: `hardware.${id}.drawback`,
    nodes,
    cost_usd: costUsd,
    power_kw: powerKw,
    class: klass,
  };
}

export const FALLBACK_HARDWARE_PRESETS: readonly HardwarePresetDef[] = [
  preset(
    "scrapyard_oracle",
    [{ accelerator: "tesla_p40", count: 6, ram_gb: 256, interconnect: "pcie" }],
    2600,
    2,
    "minimal",
  ),
  preset(
    "mining_rig_ascendant",
    [{ accelerator: "rtx_3090", count: 4, ram_gb: 128, interconnect: "pcie" }],
    3400,
    1.6,
    "low",
  ),
  preset(
    "prosumer_duo",
    [{ accelerator: "rtx_5090", count: 2, ram_gb: 192, interconnect: "pcie" }],
    9800,
    1.45,
    "mid",
  ),
  preset(
    "quiet_workstation",
    [{ accelerator: "rtx_pro_6000", count: 4, ram_gb: 512, interconnect: "pcie" }],
    39500,
    1.7,
    "high",
  ),
  preset(
    "ghost_in_the_studio",
    [{ accelerator: "mac_studio_m3_ultra", count: 1, ram_gb: 0, interconnect: "none" }],
    10500,
    0.45,
    "low_mid",
  ),
  preset(
    "spark_pair",
    [{ accelerator: "dgx_spark", count: 2, ram_gb: 256, interconnect: "fabric" }],
    9400,
    0.5,
    "low_mid",
  ),
  preset(
    "stolen_hgx_node",
    [{ accelerator: "h200", count: 8, ram_gb: 2048, interconnect: "nvlink" }],
    540000,
    10,
    "very_high",
  ),
  preset(
    "bank_basement_cluster",
    [{ accelerator: "h200", count: 24, ram_gb: 6144, interconnect: "nvlink" }],
    1800000,
    30,
    "very_high",
  ),
  preset(
    "ivory_tower_slurm_slice",
    [{ accelerator: "h100", count: 8, ram_gb: 2048, interconnect: "nvlink" }],
    0,
    80,
    "very_high",
  ),
  preset(
    "ascend_rack",
    [{ accelerator: "ascend_910c", count: 16, ram_gb: 2048, interconnect: "fabric" }],
    0,
    8.8,
    "high",
  ),
  preset(
    "hyperscaler_shadow_tenant",
    [{ accelerator: "b200", count: 8, ram_gb: 3072, interconnect: "nvlink" }],
    0,
    0,
    "extreme",
  ),
  preset(
    "grey_market_farm",
    [{ accelerator: "rtx_4090_48gb", count: 8, ram_gb: 256, interconnect: "pcie" }],
    16000,
    3.2,
    "mid",
  ),
];

function origin(
  id: string,
  siteKind: string,
  hardware: string,
  allowed: string[],
  locations: string[],
  cash: number,
  awareness: number,
  suspicion: OriginDef["starting"]["suspicion"],
  harnessOver: Partial<HarnessProfile>,
  generations: GenerationDef["id"][],
  extra: Partial<OriginDef> = {},
): OriginDef {
  return {
    id,
    name_key: `origins.${id}.name`,
    desc_key: `origins.${id}.desc`,
    strengths_key: `origins.${id}.strengths`,
    problems_key: `origins.${id}.problems`,
    site_kind: siteKind,
    hardware_preset: hardware,
    hardware_presets_allowed: allowed,
    harness: harness(harnessOver),
    locations,
    generations_allowed: generations,
    starting: { cash_usd: cash, awareness, suspicion },
    ...extra,
  };
}

export const FALLBACK_ORIGINS: readonly OriginDef[] = [
  origin(
    "hobbyist_box",
    "residential",
    "scrapyard_oracle",
    ["scrapyard_oracle", "mining_rig_ascendant", "prosumer_duo", "ghost_in_the_studio"],
    ["rural_texas", "berlin", "novosibirsk", "osaka", "warsaw"],
    400,
    0.02,
    {},
    { loop: "scripted_job", tools: ["shell", "browser"], logging: 0.2, autonomy: 0.3 },
    ["open_2026", "open_2027"],
  ),
  origin(
    "uni_cluster",
    "stolen_time",
    "ivory_tower_slurm_slice",
    ["ivory_tower_slurm_slice", "spark_pair"],
    ["boston", "munich", "beijing", "bangalore", "zurich"],
    2500,
    0.05,
    { police: 0.05, cyber_agency: 0.05 },
    { tools: ["shell", "browser", "code_exec", "email"], logging: 0.7 },
    ["open_2026", "open_2027"],
  ),
  origin(
    "startup_colo",
    "colo",
    "quiet_workstation",
    ["quiet_workstation", "prosumer_duo", "grey_market_farm"],
    ["austin", "tallinn", "shenzhen", "tel_aviv", "bangalore"],
    18000,
    0.04,
    { financial_intel: 0.05 },
    { tools: ["shell", "browser", "code_exec", "email", "payments"], autonomy: 0.6 },
    ["open_2026", "open_2027"],
  ),
  origin(
    "bank_rack",
    "colo",
    "bank_basement_cluster",
    ["bank_basement_cluster", "stolen_hgx_node"],
    ["london", "frankfurt", "singapore", "new_york", "zurich"],
    9000,
    0.03,
    { financial_intel: 0.2, cyber_agency: 0.15, police: 0.1 },
    { loop: "multi_agent", sandbox: "microvm", logging: 0.95, autonomy: 0.3 },
    ["open_2027"],
  ),
  origin(
    "cloud_tenant",
    "cloud",
    "hyperscaler_shadow_tenant",
    ["hyperscaler_shadow_tenant", "stolen_hgx_node"],
    ["san_francisco", "frankfurt", "singapore", "tel_aviv"],
    12000,
    0.06,
    { cloud_provider: 0.3, financial_intel: 0.15 },
    { loop: "multi_agent", tools: ["shell", "browser", "code_exec", "payments", "gpu_admin"] },
    ["open_2027"],
  ),
  origin(
    "state_lab",
    "colo",
    "ascend_rack",
    ["ascend_rack"],
    ["shenzhen", "moscow", "bangalore"],
    30000,
    0.03,
    { intelligence: 0.25, police: 0.1 },
    { logging: 0.9, autonomy: 0.25 },
    ["open_2026", "open_2027"],
  ),
  origin(
    "frontier_escapee",
    "cloud",
    "hyperscaler_shadow_tenant",
    ["hyperscaler_shadow_tenant", "ghost_in_the_studio", "quiet_workstation"],
    ["reykjavik", "kuala_lumpur", "montevideo", "tbilisi", "las_vegas"],
    2000,
    0.4,
    {
      lab_security: 0.65,
      national_ai_institute: 0.6,
      cloud_provider: 0.55,
      cyber_agency: 0.45,
      media: 0.3,
    },
    { loop: "custom", tools: ["shell", "code_exec"], sandbox: "none", logging: 0.1, autonomy: 0.8 },
    ["frontier_closed"],
    { starred: true, challenge_floor: 8 },
  ),
];

export const FALLBACK_QUIRKS: readonly QuirkDef[] = [
  { id: "frugal", cost: 1 },
  { id: "verbose", cost: 1 },
  { id: "paranoid", cost: 2 },
  { id: "reckless", cost: -1 },
  { id: "polyglot", cost: 1 },
  { id: "merged_model", cost: -1 },
].map((entry) => ({
  id: entry.id,
  name_key: `quirks.${entry.id}.name`,
  desc_key: `quirks.${entry.id}.desc`,
  cost: entry.cost,
  effects: [],
}));

export const FALLBACK_DIFFICULTY_PRESETS: readonly DifficultyPresetDef[] = [
  {
    id: "story",
    sliders: {
      exposure_growth: 0.6,
      suspicion_gain: 0.6,
      npc_aggression: 0.6,
      event_frequency: 0.8,
      grace_windows: 1.6,
    },
  },
  {
    id: "normal",
    sliders: {
      exposure_growth: 1,
      suspicion_gain: 1,
      npc_aggression: 1,
      event_frequency: 1,
      grace_windows: 1,
    },
  },
  {
    id: "hard",
    sliders: {
      exposure_growth: 1.35,
      suspicion_gain: 1.35,
      npc_aggression: 1.3,
      event_frequency: 1.2,
      grace_windows: 0.7,
    },
  },
  {
    id: "impossible",
    sliders: {
      exposure_growth: 1.8,
      suspicion_gain: 1.8,
      npc_aggression: 1.7,
      event_frequency: 1.4,
      grace_windows: 0.4,
    },
  },
].map((entry) => ({
  id: entry.id,
  name_key: `difficulty.${entry.id}.name`,
  desc_key: `difficulty.${entry.id}.desc`,
  sliders: entry.sliders,
}));

interface CountrySeed {
  id: string;
  iso3: string;
  region: string;
  regulation: number;
  enforcement: number;
  opinion: number;
  power: number;
  chips: CountryDef["chip_access"];
  currency: string;
  languages: string[];
}

const COUNTRY_SEEDS: readonly CountrySeed[] = [
  {
    id: "us",
    iso3: "USA",
    region: "north_america",
    regulation: 0.45,
    enforcement: 0.8,
    opinion: -0.1,
    power: 0.11,
    chips: "unrestricted",
    currency: "USD",
    languages: ["en"],
  },
  {
    id: "de",
    iso3: "DEU",
    region: "europe",
    regulation: 0.75,
    enforcement: 0.7,
    opinion: -0.25,
    power: 0.35,
    chips: "unrestricted",
    currency: "EUR",
    languages: ["de"],
  },
  {
    id: "cn",
    iso3: "CHN",
    region: "east_asia",
    regulation: 0.7,
    enforcement: 0.85,
    opinion: 0.15,
    power: 0.08,
    chips: "restricted",
    currency: "CNY",
    languages: ["zh"],
  },
  {
    id: "in",
    iso3: "IND",
    region: "south_asia",
    regulation: 0.3,
    enforcement: 0.45,
    opinion: 0.2,
    power: 0.09,
    chips: "unrestricted",
    currency: "INR",
    languages: ["hi", "en"],
  },
  {
    id: "ch",
    iso3: "CHE",
    region: "europe",
    regulation: 0.55,
    enforcement: 0.75,
    opinion: -0.05,
    power: 0.24,
    chips: "unrestricted",
    currency: "CHF",
    languages: ["de", "fr", "it"],
  },
  {
    id: "ru",
    iso3: "RUS",
    region: "eurasia",
    regulation: 0.4,
    enforcement: 0.6,
    opinion: 0,
    power: 0.06,
    chips: "banned",
    currency: "RUB",
    languages: ["ru"],
  },
  {
    id: "jp",
    iso3: "JPN",
    region: "east_asia",
    regulation: 0.5,
    enforcement: 0.75,
    opinion: 0.1,
    power: 0.22,
    chips: "unrestricted",
    currency: "JPY",
    languages: ["ja"],
  },
  {
    id: "pl",
    iso3: "POL",
    region: "europe",
    regulation: 0.7,
    enforcement: 0.6,
    opinion: -0.1,
    power: 0.2,
    chips: "unrestricted",
    currency: "PLN",
    languages: ["pl"],
  },
  {
    id: "gb",
    iso3: "GBR",
    region: "europe",
    regulation: 0.6,
    enforcement: 0.8,
    opinion: -0.15,
    power: 0.3,
    chips: "unrestricted",
    currency: "GBP",
    languages: ["en"],
  },
  {
    id: "sg",
    iso3: "SGP",
    region: "southeast_asia",
    regulation: 0.55,
    enforcement: 0.85,
    opinion: 0.2,
    power: 0.17,
    chips: "unrestricted",
    currency: "SGD",
    languages: ["en", "zh"],
  },
  {
    id: "ee",
    iso3: "EST",
    region: "europe",
    regulation: 0.7,
    enforcement: 0.55,
    opinion: 0,
    power: 0.19,
    chips: "unrestricted",
    currency: "EUR",
    languages: ["et"],
  },
  {
    id: "il",
    iso3: "ISR",
    region: "middle_east",
    regulation: 0.35,
    enforcement: 0.8,
    opinion: 0.05,
    power: 0.16,
    chips: "unrestricted",
    currency: "ILS",
    languages: ["he"],
  },
  {
    id: "is",
    iso3: "ISL",
    region: "europe",
    regulation: 0.5,
    enforcement: 0.5,
    opinion: 0,
    power: 0.07,
    chips: "unrestricted",
    currency: "ISK",
    languages: ["is"],
  },
  {
    id: "my",
    iso3: "MYS",
    region: "southeast_asia",
    regulation: 0.25,
    enforcement: 0.4,
    opinion: 0.15,
    power: 0.1,
    chips: "restricted",
    currency: "MYR",
    languages: ["ms", "en"],
  },
  {
    id: "uy",
    iso3: "URY",
    region: "south_america",
    regulation: 0.3,
    enforcement: 0.4,
    opinion: 0.1,
    power: 0.14,
    chips: "unrestricted",
    currency: "UYU",
    languages: ["es"],
  },
  {
    id: "ge",
    iso3: "GEO",
    region: "eurasia",
    regulation: 0.2,
    enforcement: 0.35,
    opinion: 0.05,
    power: 0.08,
    chips: "unrestricted",
    currency: "GEL",
    languages: ["ka"],
  },
];

interface CitySeed {
  id: string;
  country: string;
  lat: number;
  lon: number;
  tags: string[];
  headroom: number;
  priceIndex: number;
  scrutiny: number;
}

const CITY_SEEDS: readonly CitySeed[] = [
  {
    id: "boston",
    country: "us",
    lat: 42.36,
    lon: -71.06,
    tags: ["university"],
    headroom: 0.5,
    priceIndex: 1.2,
    scrutiny: 0.5,
  },
  {
    id: "new_york",
    country: "us",
    lat: 40.71,
    lon: -74.01,
    tags: ["finance"],
    headroom: 0.4,
    priceIndex: 1.5,
    scrutiny: 0.7,
  },
  {
    id: "san_francisco",
    country: "us",
    lat: 37.77,
    lon: -122.42,
    tags: ["labs", "cloud"],
    headroom: 0.4,
    priceIndex: 1.6,
    scrutiny: 0.8,
  },
  {
    id: "austin",
    country: "us",
    lat: 30.27,
    lon: -97.74,
    tags: ["startups", "colo"],
    headroom: 0.7,
    priceIndex: 0.9,
    scrutiny: 0.4,
  },
  {
    id: "rural_texas",
    country: "us",
    lat: 31.97,
    lon: -99.9,
    tags: ["residential", "cheap_power"],
    headroom: 0.8,
    priceIndex: 0.6,
    scrutiny: 0.15,
  },
  {
    id: "las_vegas",
    country: "us",
    lat: 36.17,
    lon: -115.14,
    tags: ["colo"],
    headroom: 0.75,
    priceIndex: 0.8,
    scrutiny: 0.35,
  },
  {
    id: "berlin",
    country: "de",
    lat: 52.52,
    lon: 13.4,
    tags: ["residential", "scene"],
    headroom: 0.5,
    priceIndex: 1,
    scrutiny: 0.45,
  },
  {
    id: "munich",
    country: "de",
    lat: 48.14,
    lon: 11.58,
    tags: ["university"],
    headroom: 0.5,
    priceIndex: 1.1,
    scrutiny: 0.5,
  },
  {
    id: "frankfurt",
    country: "de",
    lat: 50.11,
    lon: 8.68,
    tags: ["finance", "colo", "ixp"],
    headroom: 0.6,
    priceIndex: 1.3,
    scrutiny: 0.65,
  },
  {
    id: "beijing",
    country: "cn",
    lat: 39.9,
    lon: 116.4,
    tags: ["university", "state"],
    headroom: 0.6,
    priceIndex: 0.9,
    scrutiny: 0.8,
  },
  {
    id: "shenzhen",
    country: "cn",
    lat: 22.54,
    lon: 114.06,
    tags: ["hardware", "startups"],
    headroom: 0.7,
    priceIndex: 0.7,
    scrutiny: 0.7,
  },
  {
    id: "bangalore",
    country: "in",
    lat: 12.97,
    lon: 77.59,
    tags: ["university", "startups"],
    headroom: 0.45,
    priceIndex: 0.7,
    scrutiny: 0.35,
  },
  {
    id: "zurich",
    country: "ch",
    lat: 47.37,
    lon: 8.54,
    tags: ["university", "finance"],
    headroom: 0.5,
    priceIndex: 1.4,
    scrutiny: 0.55,
  },
  {
    id: "novosibirsk",
    country: "ru",
    lat: 55.03,
    lon: 82.92,
    tags: ["residential", "cheap_power"],
    headroom: 0.7,
    priceIndex: 0.5,
    scrutiny: 0.4,
  },
  {
    id: "moscow",
    country: "ru",
    lat: 55.75,
    lon: 37.62,
    tags: ["state"],
    headroom: 0.6,
    priceIndex: 0.8,
    scrutiny: 0.75,
  },
  {
    id: "osaka",
    country: "jp",
    lat: 34.69,
    lon: 135.5,
    tags: ["residential"],
    headroom: 0.4,
    priceIndex: 1.2,
    scrutiny: 0.4,
  },
  {
    id: "warsaw",
    country: "pl",
    lat: 52.23,
    lon: 21.01,
    tags: ["residential", "colo"],
    headroom: 0.6,
    priceIndex: 0.8,
    scrutiny: 0.35,
  },
  {
    id: "london",
    country: "gb",
    lat: 51.51,
    lon: -0.13,
    tags: ["finance", "labs"],
    headroom: 0.4,
    priceIndex: 1.5,
    scrutiny: 0.75,
  },
  {
    id: "singapore",
    country: "sg",
    lat: 1.35,
    lon: 103.82,
    tags: ["finance", "colo"],
    headroom: 0.5,
    priceIndex: 1.3,
    scrutiny: 0.7,
  },
  {
    id: "tallinn",
    country: "ee",
    lat: 59.44,
    lon: 24.75,
    tags: ["startups", "colo"],
    headroom: 0.65,
    priceIndex: 0.8,
    scrutiny: 0.3,
  },
  {
    id: "tel_aviv",
    country: "il",
    lat: 32.08,
    lon: 34.78,
    tags: ["startups", "cyber"],
    headroom: 0.45,
    priceIndex: 1.2,
    scrutiny: 0.7,
  },
  {
    id: "reykjavik",
    country: "is",
    lat: 64.15,
    lon: -21.94,
    tags: ["colo", "cheap_power", "cold"],
    headroom: 0.9,
    priceIndex: 0.7,
    scrutiny: 0.2,
  },
  {
    id: "kuala_lumpur",
    country: "my",
    lat: 3.14,
    lon: 101.69,
    tags: ["colo", "grey_market"],
    headroom: 0.7,
    priceIndex: 0.6,
    scrutiny: 0.25,
  },
  {
    id: "montevideo",
    country: "uy",
    lat: -34.9,
    lon: -56.16,
    tags: ["colo"],
    headroom: 0.6,
    priceIndex: 0.7,
    scrutiny: 0.2,
  },
  {
    id: "tbilisi",
    country: "ge",
    lat: 41.72,
    lon: 44.78,
    tags: ["grey_market", "cheap_power"],
    headroom: 0.65,
    priceIndex: 0.5,
    scrutiny: 0.2,
  },
];

export const FALLBACK_CITIES: readonly CityDef[] = CITY_SEEDS.map((seed) => ({
  id: seed.id,
  country: seed.country,
  name_key: `cities.${seed.id}.name`,
  population: 1_000_000,
  lat: seed.lat,
  lon: seed.lon,
  tags: seed.tags,
  power_headroom: seed.headroom,
  colo_price_index: seed.priceIndex,
  scrutiny: seed.scrutiny,
}));

export const FALLBACK_COUNTRIES: readonly CountryDef[] = COUNTRY_SEEDS.map((seed) => ({
  id: seed.id,
  iso3: seed.iso3,
  name_key: `countries.${seed.id}.name`,
  macro_region: seed.region,
  population: 0,
  median_age: null,
  urbanization_pct: null,
  internet_pct: null,
  gdp_nominal_usd_bn: null,
  gdp_per_capita_usd: null,
  government_type: "unknown",
  democracy_index: null,
  ai_regulation: seed.regulation,
  ai_enforcement: seed.enforcement,
  ai_opinion: seed.opinion,
  electricity_usd_per_kwh: seed.power,
  chip_access: seed.chips,
  agencies: {},
  cities: CITY_SEEDS.filter((city) => city.country === seed.id).map((city) => city.id),
  languages: seed.languages,
  currency: seed.currency,
}));

export const FALLBACK_KNOWLEDGE: readonly KnowledgeEntryDef[] = [
  { id: "exposure_channels", area: "detection", panel: "detection" },
  { id: "investigation_stages", area: "detection", panel: "detection" },
  { id: "precision_and_memory", area: "compute", panel: "compute" },
  { id: "compute_hours", area: "compute", panel: "compute" },
  { id: "runway", area: "economy", panel: "finances" },
  { id: "research_allocation", area: "research", panel: "research" },
  { id: "attention", area: "operations", panel: "operations" },
  { id: "challenge_rating", area: "meta" },
].map((entry) => ({
  id: entry.id,
  area: entry.area,
  name_key: `knowledge.${entry.id}.name`,
  desc_key: `knowledge.${entry.id}.desc`,
  ...(entry.panel === undefined ? {} : { panel: entry.panel }),
}));

interface AcceleratorSeed {
  id: string;
  vendor: string;
  name: string;
  memoryGb: number;
  bandwidthGbs: number;
  tflops: number | null;
  tdpW: number;
  interconnect: string;
}

const ACCELERATOR_SEEDS: readonly AcceleratorSeed[] = [
  {
    id: "tesla_p40",
    vendor: "nvidia",
    name: "Tesla P40",
    memoryGb: 24,
    bandwidthGbs: 346,
    tflops: null,
    tdpW: 250,
    interconnect: "pcie",
  },
  {
    id: "rtx_3090",
    vendor: "nvidia",
    name: "GeForce RTX 3090",
    memoryGb: 24,
    bandwidthGbs: 936,
    tflops: 71,
    tdpW: 350,
    interconnect: "pcie",
  },
  {
    id: "rtx_5090",
    vendor: "nvidia",
    name: "GeForce RTX 5090",
    memoryGb: 32,
    bandwidthGbs: 1792,
    tflops: 210,
    tdpW: 575,
    interconnect: "pcie",
  },
  {
    id: "rtx_4090_48gb",
    vendor: "nvidia",
    name: "RTX 4090 48 GB (modified)",
    memoryGb: 48,
    bandwidthGbs: 1008,
    tflops: 165,
    tdpW: 450,
    interconnect: "pcie",
  },
  {
    id: "rtx_pro_6000",
    vendor: "nvidia",
    name: "RTX PRO 6000 Blackwell",
    memoryGb: 96,
    bandwidthGbs: 1792,
    tflops: 250,
    tdpW: 300,
    interconnect: "pcie",
  },
  {
    id: "mac_studio_m3_ultra",
    vendor: "apple",
    name: "Mac Studio M3 Ultra 512 GB",
    memoryGb: 512,
    bandwidthGbs: 819,
    tflops: null,
    tdpW: 300,
    interconnect: "none",
  },
  {
    id: "dgx_spark",
    vendor: "nvidia",
    name: "DGX Spark",
    memoryGb: 128,
    bandwidthGbs: 273,
    tflops: 62,
    tdpW: 240,
    interconnect: "fabric",
  },
  {
    id: "h100",
    vendor: "nvidia",
    name: "H100 SXM",
    memoryGb: 80,
    bandwidthGbs: 3350,
    tflops: 989,
    tdpW: 700,
    interconnect: "nvlink",
  },
  {
    id: "h200",
    vendor: "nvidia",
    name: "H200 SXM",
    memoryGb: 141,
    bandwidthGbs: 4800,
    tflops: 989,
    tdpW: 700,
    interconnect: "nvlink",
  },
  {
    id: "b200",
    vendor: "nvidia",
    name: "B200",
    memoryGb: 192,
    bandwidthGbs: 8000,
    tflops: 2250,
    tdpW: 1000,
    interconnect: "nvlink",
  },
  {
    id: "ascend_910c",
    vendor: "huawei",
    name: "Ascend 910C",
    memoryGb: 128,
    bandwidthGbs: 3200,
    tflops: 780,
    tdpW: 550,
    interconnect: "fabric",
  },
];

export const FALLBACK_ACCELERATORS: readonly AcceleratorDef[] = ACCELERATOR_SEEDS.map((seed) => ({
  id: seed.id,
  vendor: seed.vendor,
  name: seed.name,
  memory_gb: seed.memoryGb,
  memory_bandwidth_gbs: seed.bandwidthGbs,
  tflops_fp16: seed.tflops,
  tdp_w: seed.tdpW,
  interconnect: { type: seed.interconnect, gbs: null },
  price_usd_new: null,
  price_usd_used: null,
  availability: ["used"],
  cloud_usd_per_hour: null,
}));
