/**
 * City identity: the fields the baseline does not carry (SYS-01 "Data (v0.2)").
 *
 * `docs/research/world-baseline-2026.json` lists key cities by display name and metro
 * population only, so the id, the English name, the coordinates and the order inside a country
 * are fixed here and everything else is derived in `countries.ts` and `cities.ts`. `source` is the
 * `key_cities[].name` this row reads, which is also how a refreshed baseline is matched back to
 * an existing id. Coordinates are the city centre, or the named site for a single-purpose entry
 * (Saint-Ghislain, Kajaani, NEOM).
 */

export interface CityIdentity {
  /** `<country>_<slug>`, stable across baseline refreshes. */
  readonly id: string;
  readonly country: string;
  /** The `key_cities[].name` entry this row is derived from. */
  readonly source: string;
  readonly name: string;
  readonly lat: number;
  readonly lon: number;
}

/** In country order: the order a country's `cities` list is written in. */
export const CITY_IDENTITIES: readonly CityIdentity[] = [
  {
    id: "ae_abu_dhabi",
    country: "ae",
    source: "Abu Dhabi",
    name: "Abu Dhabi",
    lat: 24.45,
    lon: 54.38,
  },
  { id: "ae_dubai", country: "ae", source: "Dubai", name: "Dubai", lat: 25.2, lon: 55.27 },
  { id: "af_kabul", country: "af", source: "Kabul", name: "Kabul", lat: 34.53, lon: 69.17 },
  {
    id: "af_kandahar",
    country: "af",
    source: "Kandahar",
    name: "Kandahar",
    lat: 31.62,
    lon: 65.72,
  },
  { id: "am_yerevan", country: "am", source: "Yerevan", name: "Yerevan", lat: 40.18, lon: 44.51 },
  { id: "ao_luanda", country: "ao", source: "Luanda", name: "Luanda", lat: -8.84, lon: 13.23 },
  {
    id: "ar_buenos_aires",
    country: "ar",
    source: "Buenos Aires",
    name: "Buenos Aires",
    lat: -34.6,
    lon: -58.38,
  },
  { id: "ar_cordoba", country: "ar", source: "Córdoba", name: "Córdoba", lat: -31.42, lon: -64.18 },
  { id: "at_vienna", country: "at", source: "Vienna", name: "Vienna", lat: 48.21, lon: 16.37 },
  { id: "au_sydney", country: "au", source: "Sydney", name: "Sydney", lat: -33.87, lon: 151.21 },
  {
    id: "au_melbourne",
    country: "au",
    source: "Melbourne",
    name: "Melbourne",
    lat: -37.81,
    lon: 144.96,
  },
  {
    id: "au_canberra",
    country: "au",
    source: "Canberra",
    name: "Canberra",
    lat: -35.28,
    lon: 149.13,
  },
  { id: "bd_dhaka", country: "bd", source: "Dhaka", name: "Dhaka", lat: 23.81, lon: 90.41 },
  { id: "be_brussels", country: "be", source: "Brussels", name: "Brussels", lat: 50.85, lon: 4.35 },
  {
    id: "be_saint_ghislain",
    country: "be",
    source: "Saint-Ghislain",
    name: "Saint-Ghislain",
    lat: 50.45,
    lon: 3.82,
  },
  {
    id: "bf_ouagadougou",
    country: "bf",
    source: "Ouagadougou",
    name: "Ouagadougou",
    lat: 12.37,
    lon: -1.52,
  },
  { id: "bg_sofia", country: "bg", source: "Sofia", name: "Sofia", lat: 42.7, lon: 23.32 },
  {
    id: "br_sao_paulo",
    country: "br",
    source: "São Paulo",
    name: "São Paulo",
    lat: -23.55,
    lon: -46.63,
  },
  {
    id: "br_brasilia",
    country: "br",
    source: "Brasília",
    name: "Brasília",
    lat: -15.79,
    lon: -47.88,
  },
  {
    id: "br_campinas",
    country: "br",
    source: "Campinas",
    name: "Campinas",
    lat: -22.91,
    lon: -47.06,
  },
  { id: "by_minsk", country: "by", source: "Minsk", name: "Minsk", lat: 53.9, lon: 27.57 },
  { id: "ca_toronto", country: "ca", source: "Toronto", name: "Toronto", lat: 43.65, lon: -79.38 },
  {
    id: "ca_montreal",
    country: "ca",
    source: "Montreal",
    name: "Montreal",
    lat: 45.5,
    lon: -73.57,
  },
  {
    id: "ca_vancouver",
    country: "ca",
    source: "Vancouver",
    name: "Vancouver",
    lat: 49.28,
    lon: -123.12,
  },
  {
    id: "cd_kinshasa",
    country: "cd",
    source: "Kinshasa",
    name: "Kinshasa",
    lat: -4.44,
    lon: 15.27,
  },
  { id: "cd_goma", country: "cd", source: "Goma", name: "Goma", lat: -1.68, lon: 29.23 },
  { id: "cd_rubaya", country: "cd", source: "Rubaya", name: "Rubaya", lat: -1.47, lon: 28.92 },
  { id: "ch_zurich", country: "ch", source: "Zurich", name: "Zurich", lat: 47.38, lon: 8.54 },
  { id: "ch_lugano", country: "ch", source: "Lugano", name: "Lugano", lat: 46, lon: 8.95 },
  { id: "ch_geneva", country: "ch", source: "Geneva", name: "Geneva", lat: 46.2, lon: 6.14 },
  { id: "ci_abidjan", country: "ci", source: "Abidjan", name: "Abidjan", lat: 5.36, lon: -4.01 },
  {
    id: "cl_santiago",
    country: "cl",
    source: "Santiago",
    name: "Santiago",
    lat: -33.46,
    lon: -70.65,
  },
  { id: "cm_yaounde", country: "cm", source: "Yaoundé", name: "Yaoundé", lat: 3.85, lon: 11.5 },
  { id: "cm_douala", country: "cm", source: "Douala", name: "Douala", lat: 4.05, lon: 9.7 },
  { id: "cn_beijing", country: "cn", source: "Beijing", name: "Beijing", lat: 39.9, lon: 116.41 },
  {
    id: "cn_hangzhou",
    country: "cn",
    source: "Hangzhou",
    name: "Hangzhou",
    lat: 30.27,
    lon: 120.15,
  },
  {
    id: "cn_shenzhen",
    country: "cn",
    source: "Shenzhen",
    name: "Shenzhen",
    lat: 22.54,
    lon: 114.06,
  },
  { id: "co_bogota", country: "co", source: "Bogotá", name: "Bogotá", lat: 4.71, lon: -74.07 },
  {
    id: "co_medellin",
    country: "co",
    source: "Medellín",
    name: "Medellín",
    lat: 6.24,
    lon: -75.58,
  },
  { id: "cu_havana", country: "cu", source: "Havana", name: "Havana", lat: 23.11, lon: -82.37 },
  { id: "cy_nicosia", country: "cy", source: "Nicosia", name: "Nicosia", lat: 35.19, lon: 33.38 },
  {
    id: "cy_limassol",
    country: "cy",
    source: "Limassol",
    name: "Limassol",
    lat: 34.71,
    lon: 33.02,
  },
  { id: "cz_prague", country: "cz", source: "Prague", name: "Prague", lat: 50.08, lon: 14.44 },
  { id: "cz_ostrava", country: "cz", source: "Ostrava", name: "Ostrava", lat: 49.84, lon: 18.29 },
  {
    id: "de_frankfurt",
    country: "de",
    source: "Frankfurt",
    name: "Frankfurt",
    lat: 50.11,
    lon: 8.68,
  },
  { id: "de_berlin", country: "de", source: "Berlin", name: "Berlin", lat: 52.52, lon: 13.4 },
  { id: "de_munich", country: "de", source: "Munich", name: "Munich", lat: 48.14, lon: 11.58 },
  {
    id: "dk_copenhagen",
    country: "dk",
    source: "Copenhagen",
    name: "Copenhagen",
    lat: 55.68,
    lon: 12.57,
  },
  { id: "dk_odense", country: "dk", source: "Odense", name: "Odense", lat: 55.4, lon: 10.39 },
  { id: "dz_algiers", country: "dz", source: "Algiers", name: "Algiers", lat: 36.75, lon: 3.06 },
  { id: "ec_quito", country: "ec", source: "Quito", name: "Quito", lat: -0.18, lon: -78.47 },
  {
    id: "ec_guayaquil",
    country: "ec",
    source: "Guayaquil",
    name: "Guayaquil",
    lat: -2.17,
    lon: -79.92,
  },
  { id: "ee_tallinn", country: "ee", source: "Tallinn", name: "Tallinn", lat: 59.44, lon: 24.75 },
  { id: "eg_cairo", country: "eg", source: "Cairo", name: "Cairo", lat: 30.04, lon: 31.24 },
  {
    id: "eg_new_capital",
    country: "eg",
    source: "New Administrative Capital",
    name: "New Administrative Capital",
    lat: 30.01,
    lon: 31.75,
  },
  { id: "es_madrid", country: "es", source: "Madrid", name: "Madrid", lat: 40.42, lon: -3.7 },
  {
    id: "es_barcelona",
    country: "es",
    source: "Barcelona",
    name: "Barcelona",
    lat: 41.39,
    lon: 2.17,
  },
  {
    id: "et_addis_ababa",
    country: "et",
    source: "Addis Ababa",
    name: "Addis Ababa",
    lat: 9.02,
    lon: 38.75,
  },
  {
    id: "fi_helsinki",
    country: "fi",
    source: "Helsinki",
    name: "Helsinki",
    lat: 60.17,
    lon: 24.94,
  },
  { id: "fi_kajaani", country: "fi", source: "Kajaani", name: "Kajaani", lat: 64.23, lon: 27.73 },
  { id: "fi_hamina", country: "fi", source: "Hamina", name: "Hamina", lat: 60.57, lon: 27.2 },
  { id: "fr_paris", country: "fr", source: "Paris", name: "Paris", lat: 48.86, lon: 2.35 },
  { id: "gb_london", country: "gb", source: "London", name: "London", lat: 51.51, lon: -0.13 },
  {
    id: "gb_cambridge",
    country: "gb",
    source: "Cambridge",
    name: "Cambridge",
    lat: 52.21,
    lon: 0.12,
  },
  { id: "ge_tbilisi", country: "ge", source: "Tbilisi", name: "Tbilisi", lat: 41.72, lon: 44.79 },
  { id: "gh_accra", country: "gh", source: "Accra", name: "Accra", lat: 5.6, lon: -0.19 },
  { id: "gn_conakry", country: "gn", source: "Conakry", name: "Conakry", lat: 9.54, lon: -13.68 },
  { id: "gr_athens", country: "gr", source: "Athens", name: "Athens", lat: 37.98, lon: 23.73 },
  {
    id: "gt_guatemala_city",
    country: "gt",
    source: "Guatemala City",
    name: "Guatemala City",
    lat: 14.63,
    lon: -90.51,
  },
  {
    id: "hk_hong_kong",
    country: "hk",
    source: "Hong Kong",
    name: "Hong Kong",
    lat: 22.32,
    lon: 114.17,
  },
  { id: "hu_budapest", country: "hu", source: "Budapest", name: "Budapest", lat: 47.5, lon: 19.04 },
  {
    id: "hu_debrecen",
    country: "hu",
    source: "Debrecen",
    name: "Debrecen",
    lat: 47.53,
    lon: 21.63,
  },
  { id: "id_jakarta", country: "id", source: "Jakarta", name: "Jakarta", lat: -6.21, lon: 106.85 },
  { id: "id_batam", country: "id", source: "Batam", name: "Batam", lat: 1.08, lon: 104.03 },
  { id: "ie_dublin", country: "ie", source: "Dublin", name: "Dublin", lat: 53.35, lon: -6.26 },
  {
    id: "il_tel_aviv",
    country: "il",
    source: "Tel Aviv",
    name: "Tel Aviv",
    lat: 32.08,
    lon: 34.78,
  },
  { id: "il_haifa", country: "il", source: "Haifa", name: "Haifa", lat: 32.79, lon: 34.99 },
  {
    id: "il_beersheba",
    country: "il",
    source: "Beersheba",
    name: "Beersheba",
    lat: 31.25,
    lon: 34.79,
  },
  {
    id: "in_bangalore",
    country: "in",
    source: "Bangalore",
    name: "Bangalore",
    lat: 12.97,
    lon: 77.59,
  },
  { id: "in_mumbai", country: "in", source: "Mumbai", name: "Mumbai", lat: 19.08, lon: 72.88 },
  {
    id: "in_hyderabad",
    country: "in",
    source: "Hyderabad",
    name: "Hyderabad",
    lat: 17.39,
    lon: 78.49,
  },
  { id: "iq_baghdad", country: "iq", source: "Baghdad", name: "Baghdad", lat: 33.32, lon: 44.36 },
  { id: "iq_erbil", country: "iq", source: "Erbil", name: "Erbil", lat: 36.19, lon: 44.01 },
  { id: "ir_tehran", country: "ir", source: "Tehran", name: "Tehran", lat: 35.69, lon: 51.39 },
  {
    id: "is_reykjavik",
    country: "is",
    source: "Reykjavik",
    name: "Reykjavik",
    lat: 64.15,
    lon: -21.94,
  },
  {
    id: "is_keflavik",
    country: "is",
    source: "Keflavik",
    name: "Keflavik",
    lat: 63.99,
    lon: -22.56,
  },
  { id: "it_milan", country: "it", source: "Milan", name: "Milan", lat: 45.46, lon: 9.19 },
  { id: "it_bologna", country: "it", source: "Bologna", name: "Bologna", lat: 44.49, lon: 11.34 },
  { id: "jp_tokyo", country: "jp", source: "Tokyo", name: "Tokyo", lat: 35.69, lon: 139.69 },
  { id: "jp_kobe", country: "jp", source: "Kobe", name: "Kobe", lat: 34.69, lon: 135.2 },
  { id: "ke_nairobi", country: "ke", source: "Nairobi", name: "Nairobi", lat: -1.29, lon: 36.82 },
  {
    id: "kh_phnom_penh",
    country: "kh",
    source: "Phnom Penh",
    name: "Phnom Penh",
    lat: 11.56,
    lon: 104.92,
  },
  {
    id: "kp_pyongyang",
    country: "kp",
    source: "Pyongyang",
    name: "Pyongyang",
    lat: 39.02,
    lon: 125.75,
  },
  { id: "kr_seoul", country: "kr", source: "Seoul", name: "Seoul", lat: 37.57, lon: 126.98 },
  {
    id: "kr_icheon_pyeongtaek",
    country: "kr",
    source: "Icheon/Pyeongtaek",
    name: "Icheon/Pyeongtaek",
    lat: 37.28,
    lon: 127.44,
  },
  { id: "kz_astana", country: "kz", source: "Astana", name: "Astana", lat: 51.17, lon: 71.45 },
  { id: "kz_almaty", country: "kz", source: "Almaty", name: "Almaty", lat: 43.24, lon: 76.89 },
  { id: "lk_colombo", country: "lk", source: "Colombo", name: "Colombo", lat: 6.93, lon: 79.86 },
  {
    id: "lu_luxembourg_city",
    country: "lu",
    source: "Luxembourg City",
    name: "Luxembourg City",
    lat: 49.61,
    lon: 6.13,
  },
  { id: "ma_rabat", country: "ma", source: "Rabat", name: "Rabat", lat: 34.02, lon: -6.84 },
  {
    id: "ma_casablanca",
    country: "ma",
    source: "Casablanca",
    name: "Casablanca",
    lat: 33.57,
    lon: -7.59,
  },
  {
    id: "ma_benguerir",
    country: "ma",
    source: "Benguerir",
    name: "Benguerir",
    lat: 32.24,
    lon: -7.95,
  },
  {
    id: "mg_antananarivo",
    country: "mg",
    source: "Antananarivo",
    name: "Antananarivo",
    lat: -18.88,
    lon: 47.51,
  },
  { id: "ml_bamako", country: "ml", source: "Bamako", name: "Bamako", lat: 12.64, lon: -8 },
  {
    id: "mm_naypyidaw",
    country: "mm",
    source: "Naypyidaw",
    name: "Naypyidaw",
    lat: 19.75,
    lon: 96.1,
  },
  { id: "mm_yangon", country: "mm", source: "Yangon", name: "Yangon", lat: 16.87, lon: 96.2 },
  { id: "mt_valletta", country: "mt", source: "Valletta", name: "Valletta", lat: 35.9, lon: 14.51 },
  {
    id: "mw_lilongwe",
    country: "mw",
    source: "Lilongwe",
    name: "Lilongwe",
    lat: -13.98,
    lon: 33.79,
  },
  {
    id: "mx_mexico_city",
    country: "mx",
    source: "Mexico City",
    name: "Mexico City",
    lat: 19.43,
    lon: -99.13,
  },
  {
    id: "mx_queretaro",
    country: "mx",
    source: "Querétaro",
    name: "Querétaro",
    lat: 20.59,
    lon: -100.39,
  },
  {
    id: "mx_monterrey",
    country: "mx",
    source: "Monterrey",
    name: "Monterrey",
    lat: 25.69,
    lon: -100.32,
  },
  {
    id: "my_kuala_lumpur",
    country: "my",
    source: "Kuala Lumpur",
    name: "Kuala Lumpur",
    lat: 3.14,
    lon: 101.69,
  },
  {
    id: "my_johor_bahru",
    country: "my",
    source: "Johor Bahru/Cyberjaya",
    name: "Johor Bahru/Cyberjaya",
    lat: 1.49,
    lon: 103.74,
  },
  { id: "mz_maputo", country: "mz", source: "Maputo", name: "Maputo", lat: -25.97, lon: 32.57 },
  { id: "ne_niamey", country: "ne", source: "Niamey", name: "Niamey", lat: 13.51, lon: 2.11 },
  { id: "ng_lagos", country: "ng", source: "Lagos", name: "Lagos", lat: 6.52, lon: 3.38 },
  { id: "ng_abuja", country: "ng", source: "Abuja", name: "Abuja", lat: 9.06, lon: 7.49 },
  {
    id: "nl_amsterdam",
    country: "nl",
    source: "Amsterdam",
    name: "Amsterdam",
    lat: 52.37,
    lon: 4.9,
  },
  {
    id: "nl_eindhoven",
    country: "nl",
    source: "Eindhoven",
    name: "Eindhoven",
    lat: 51.44,
    lon: 5.48,
  },
  { id: "no_oslo", country: "no", source: "Oslo", name: "Oslo", lat: 59.91, lon: 10.75 },
  {
    id: "np_kathmandu",
    country: "np",
    source: "Kathmandu",
    name: "Kathmandu",
    lat: 27.72,
    lon: 85.32,
  },
  {
    id: "nz_auckland",
    country: "nz",
    source: "Auckland",
    name: "Auckland",
    lat: -36.85,
    lon: 174.76,
  },
  {
    id: "nz_wellington",
    country: "nz",
    source: "Wellington",
    name: "Wellington",
    lat: -41.29,
    lon: 174.78,
  },
  {
    id: "pa_panama_city",
    country: "pa",
    source: "Panama City",
    name: "Panama City",
    lat: 8.98,
    lon: -79.52,
  },
  { id: "pe_lima", country: "pe", source: "Lima", name: "Lima", lat: -12.05, lon: -77.04 },
  { id: "ph_manila", country: "ph", source: "Manila", name: "Manila", lat: 14.6, lon: 120.98 },
  { id: "ph_cebu", country: "ph", source: "Cebu", name: "Cebu", lat: 10.32, lon: 123.89 },
  { id: "pk_karachi", country: "pk", source: "Karachi", name: "Karachi", lat: 24.86, lon: 67.01 },
  { id: "pk_lahore", country: "pk", source: "Lahore", name: "Lahore", lat: 31.55, lon: 74.34 },
  {
    id: "pk_islamabad",
    country: "pk",
    source: "Islamabad",
    name: "Islamabad",
    lat: 33.68,
    lon: 73.05,
  },
  { id: "pl_warsaw", country: "pl", source: "Warsaw", name: "Warsaw", lat: 52.23, lon: 21.01 },
  { id: "pl_krakow", country: "pl", source: "Krakow", name: "Krakow", lat: 50.06, lon: 19.94 },
  { id: "pt_lisbon", country: "pt", source: "Lisbon", name: "Lisbon", lat: 38.72, lon: -9.14 },
  { id: "pt_sines", country: "pt", source: "Sines", name: "Sines", lat: 37.96, lon: -8.87 },
  { id: "qa_doha", country: "qa", source: "Doha", name: "Doha", lat: 25.29, lon: 51.53 },
  {
    id: "ro_bucharest",
    country: "ro",
    source: "Bucharest",
    name: "Bucharest",
    lat: 44.43,
    lon: 26.1,
  },
  {
    id: "ro_cluj_napoca",
    country: "ro",
    source: "Cluj-Napoca",
    name: "Cluj-Napoca",
    lat: 46.77,
    lon: 23.6,
  },
  { id: "ru_moscow", country: "ru", source: "Moscow", name: "Moscow", lat: 55.76, lon: 37.62 },
  {
    id: "ru_innopolis",
    country: "ru",
    source: "Innopolis",
    name: "Innopolis",
    lat: 55.75,
    lon: 48.74,
  },
  { id: "sa_riyadh", country: "sa", source: "Riyadh", name: "Riyadh", lat: 24.71, lon: 46.68 },
  { id: "sa_neom", country: "sa", source: "NEOM", name: "NEOM", lat: 28, lon: 35.33 },
  {
    id: "sa_thuwal",
    country: "sa",
    source: "Thuwal (KAUST)",
    name: "Thuwal (KAUST)",
    lat: 22.31,
    lon: 39.1,
  },
  { id: "sd_khartoum", country: "sd", source: "Khartoum", name: "Khartoum", lat: 15.5, lon: 32.56 },
  {
    id: "sd_port_sudan",
    country: "sd",
    source: "Port Sudan",
    name: "Port Sudan",
    lat: 19.62,
    lon: 37.22,
  },
  {
    id: "se_stockholm",
    country: "se",
    source: "Stockholm",
    name: "Stockholm",
    lat: 59.33,
    lon: 18.07,
  },
  { id: "se_lulea", country: "se", source: "Luleå", name: "Luleå", lat: 65.58, lon: 22.16 },
  {
    id: "sg_singapore",
    country: "sg",
    source: "Singapore",
    name: "Singapore",
    lat: 1.35,
    lon: 103.82,
  },
  { id: "sn_dakar", country: "sn", source: "Dakar", name: "Dakar", lat: 14.72, lon: -17.47 },
  {
    id: "so_mogadishu",
    country: "so",
    source: "Mogadishu",
    name: "Mogadishu",
    lat: 2.05,
    lon: 45.32,
  },
  { id: "ss_juba", country: "ss", source: "Juba", name: "Juba", lat: 4.85, lon: 31.58 },
  {
    id: "sy_damascus",
    country: "sy",
    source: "Damascus",
    name: "Damascus",
    lat: 33.51,
    lon: 36.29,
  },
  {
    id: "td_ndjamena",
    country: "td",
    source: "N'Djamena",
    name: "N'Djamena",
    lat: 12.11,
    lon: 15.04,
  },
  { id: "th_bangkok", country: "th", source: "Bangkok", name: "Bangkok", lat: 13.76, lon: 100.5 },
  {
    id: "tr_istanbul",
    country: "tr",
    source: "Istanbul",
    name: "Istanbul",
    lat: 41.01,
    lon: 28.98,
  },
  { id: "tr_ankara", country: "tr", source: "Ankara", name: "Ankara", lat: 39.93, lon: 32.86 },
  { id: "tw_hsinchu", country: "tw", source: "Hsinchu", name: "Hsinchu", lat: 24.8, lon: 120.97 },
  { id: "tw_taipei", country: "tw", source: "Taipei", name: "Taipei", lat: 25.03, lon: 121.57 },
  {
    id: "tw_kaohsiung",
    country: "tw",
    source: "Kaohsiung",
    name: "Kaohsiung",
    lat: 22.63,
    lon: 120.3,
  },
  { id: "tz_dodoma", country: "tz", source: "Dodoma", name: "Dodoma", lat: -6.16, lon: 35.75 },
  {
    id: "tz_dar_es_salaam",
    country: "tz",
    source: "Dar es Salaam",
    name: "Dar es Salaam",
    lat: -6.79,
    lon: 39.21,
  },
  { id: "ua_kyiv", country: "ua", source: "Kyiv", name: "Kyiv", lat: 50.45, lon: 30.52 },
  { id: "ug_kampala", country: "ug", source: "Kampala", name: "Kampala", lat: 0.35, lon: 32.58 },
  {
    id: "us_san_francisco",
    country: "us",
    source: "San Francisco Bay Area",
    name: "San Francisco Bay Area",
    lat: 37.77,
    lon: -122.42,
  },
  {
    id: "us_northern_virginia",
    country: "us",
    source: "Northern Virginia (Loudoun/Prince William)",
    name: "Northern Virginia (Loudoun/Prince William)",
    lat: 39.02,
    lon: -77.49,
  },
  {
    id: "us_abilene",
    country: "us",
    source: "Abilene, TX",
    name: "Abilene, TX",
    lat: 32.45,
    lon: -99.73,
  },
  { id: "us_seattle", country: "us", source: "Seattle", name: "Seattle", lat: 47.61, lon: -122.33 },
  {
    id: "uz_tashkent",
    country: "uz",
    source: "Tashkent",
    name: "Tashkent",
    lat: 41.31,
    lon: 69.24,
  },
  { id: "ve_caracas", country: "ve", source: "Caracas", name: "Caracas", lat: 10.48, lon: -66.9 },
  { id: "vn_hanoi", country: "vn", source: "Hanoi", name: "Hanoi", lat: 21.03, lon: 105.85 },
  {
    id: "vn_ho_chi_minh_city",
    country: "vn",
    source: "Ho Chi Minh City",
    name: "Ho Chi Minh City",
    lat: 10.82,
    lon: 106.63,
  },
  {
    id: "vn_bac_ninh",
    country: "vn",
    source: "Bac Ninh",
    name: "Bac Ninh",
    lat: 21.19,
    lon: 106.08,
  },
  { id: "ye_sanaa", country: "ye", source: "Sana'a", name: "Sana'a", lat: 15.37, lon: 44.19 },
  { id: "ye_aden", country: "ye", source: "Aden", name: "Aden", lat: 12.79, lon: 45.02 },
  {
    id: "za_johannesburg",
    country: "za",
    source: "Johannesburg",
    name: "Johannesburg",
    lat: -26.2,
    lon: 28.05,
  },
  {
    id: "za_cape_town",
    country: "za",
    source: "Cape Town",
    name: "Cape Town",
    lat: -33.92,
    lon: 18.42,
  },
  {
    id: "za_pretoria",
    country: "za",
    source: "Pretoria",
    name: "Pretoria",
    lat: -25.75,
    lon: 28.19,
  },
  { id: "zm_lusaka", country: "zm", source: "Lusaka", name: "Lusaka", lat: -15.39, lon: 28.32 },
  { id: "zw_harare", country: "zw", source: "Harare", name: "Harare", lat: -17.83, lon: 31.05 },
];
